/**
 * Bộ câu hỏi trắc nghiệm cây/trái cây trong game
 */
const QUIZ_QUESTIONS = [
  { question: 'Trái cây nào có nhiều vitamin C nhất?', options: ['Táo', 'Cam', 'Chuối', 'Nho'], answer: 'B' },
  { question: 'Trái cây nào thường có màu vàng khi chín?', options: ['Chuối', 'Táo', 'Dâu', 'Cherry'], answer: 'A' },
  { question: 'Trái cây nào có nhiều hạt nhỏ bên ngoài vỏ?', options: ['Dâu tây', 'Cam', 'Táo', 'Lê'], answer: 'A' },
  { question: 'Trái cây nào thường được dùng để làm nước cam?', options: ['Chanh', 'Cam', 'Bưởi', 'Táo'], answer: 'B' },
  { question: 'Trái cây nào thường có màu tím hoặc xanh?', options: ['Chuối', 'Nho', 'Xoài', 'Dứa'], answer: 'B' },
  { question: 'Trái cây nào có lớp vỏ gai bên ngoài?', options: ['Dứa', 'Chuối', 'Táo', 'Nho'], answer: 'A' },
  { question: 'Trái cây nào thường có hình tròn và màu đỏ?', options: ['Táo', 'Chuối', 'Lê', 'Dứa'], answer: 'A' },
  { question: 'Trái cây nào thường được dùng làm sinh tố?', options: ['Chuối', 'Dưa hấu', 'Xoài', 'Tất cả các đáp án trên'], answer: 'D' },
  { question: 'Trái cây nào có vỏ màu xanh và ruột đỏ?', options: ['Dưa hấu', 'Táo', 'Lê', 'Cam'], answer: 'A' },
  { question: 'Trái cây nào thường có mùi thơm mạnh?', options: ['Sầu riêng', 'Táo', 'Lê', 'Nho'], answer: 'A' },
  { question: 'Trái cây nào có nhiều kali?', options: ['Chuối', 'Táo', 'Dâu', 'Cherry'], answer: 'A' },
  { question: 'Trái cây nào thường có vị chua?', options: ['Chanh', 'Chuối', 'Xoài chín', 'Dưa hấu'], answer: 'A' },
  { question: 'Trái cây nào có ruột màu cam?', options: ['Xoài', 'Táo', 'Lê', 'Nho'], answer: 'A' },
  { question: 'Trái cây nào có vỏ màu xanh và ruột trắng?', options: ['Lê', 'Táo', 'Chuối', 'Dâu'], answer: 'A' },
  { question: 'Trái cây nào có nhiều nước nhất?', options: ['Dưa hấu', 'Chuối', 'Táo', 'Xoài'], answer: 'A' },
  { question: 'Trái cây nào thường được dùng làm nước chanh?', options: ['Chanh', 'Cam', 'Bưởi', 'Táo'], answer: 'A' },
  { question: 'Trái cây nào có hạt lớn ở giữa?', options: ['Xoài', 'Nho', 'Dâu', 'Cherry'], answer: 'A' },
  { question: 'Trái cây nào có thể có màu xanh hoặc đỏ?', options: ['Táo', 'Chuối', 'Dứa', 'Chanh'], answer: 'A' },
  { question: 'Trái cây nào có vỏ cứng và nhiều gai?', options: ['Sầu riêng', 'Chuối', 'Nho', 'Táo'], answer: 'A' },
  { question: 'Trái cây nào thường được ăn vào mùa hè?', options: ['Dưa hấu', 'Táo', 'Lê', 'Cam'], answer: 'A' },
  { question: 'Trái cây nào thường có hình cong?', options: ['Chuối', 'Táo', 'Lê', 'Cam'], answer: 'A' },
  { question: 'Trái cây nào có nhiều múi?', options: ['Cam', 'Chuối', 'Táo', 'Lê'], answer: 'A' },
  { question: 'Trái cây nào thường dùng làm mứt?', options: ['Dâu tây', 'Chuối', 'Lê', 'Dứa'], answer: 'A' },
  { question: 'Trái cây nào có ruột màu vàng?', options: ['Dứa', 'Táo', 'Nho', 'Cherry'], answer: 'A' },
  { question: 'Trái cây nào nhỏ và mọc thành chùm?', options: ['Nho', 'Táo', 'Lê', 'Xoài'], answer: 'A' },
  { question: 'Trái cây nào có lớp vỏ dễ bóc?', options: ['Chuối', 'Táo', 'Lê', 'Nho'], answer: 'A' },
  { question: 'Trái cây nào có thể làm salad trái cây?', options: ['Táo', 'Nho', 'Dứa', 'Tất cả các đáp án trên'], answer: 'D' },
  { question: 'Trái cây nào có vị ngọt khi chín?', options: ['Xoài', 'Chuối', 'Dưa hấu', 'Tất cả các đáp án trên'], answer: 'D' },
  { question: 'Trái cây nào có màu đỏ nhỏ?', options: ['Cherry', 'Chuối', 'Cam', 'Lê'], answer: 'A' },
  { question: 'Trái cây nào thường dùng làm nước ép?', options: ['Cam', 'Táo', 'Dứa', 'Tất cả các đáp án trên'], answer: 'D' },
  { question: 'Trái cây nào có vỏ màu tím đậm?', options: ['Nho tím', 'Chuối', 'Táo', 'Cam'], answer: 'A' },
  { question: 'Trái cây nào có nhiều vitamin A?', options: ['Xoài', 'Chuối', 'Lê', 'Nho'], answer: 'A' },
  { question: 'Trái cây nào thường mọc ở vùng nhiệt đới?', options: ['Dứa', 'Táo', 'Lê', 'Cherry'], answer: 'A' },
  { question: 'Trái cây nào có hạt nhỏ bên trong ruột?', options: ['Ổi', 'Chuối', 'Cam', 'Táo'], answer: 'A' },
  { question: 'Trái cây nào thường được ăn lạnh vào mùa hè?', options: ['Dưa hấu', 'Táo', 'Lê', 'Chuối'], answer: 'A' },
  { question: 'Trái cây nào có vỏ màu vàng và nhiều mắt?', options: ['Dứa', 'Chuối', 'Lê', 'Táo'], answer: 'A' },
  { question: 'Trái cây nào có mùi thơm mạnh đặc trưng?', options: ['Sầu riêng', 'Táo', 'Nho', 'Lê'], answer: 'A' },
  { question: 'Trái cây nào thường dùng làm bánh táo?', options: ['Táo', 'Chuối', 'Nho', 'Dứa'], answer: 'A' },
  { question: 'Trái cây nào thường có vị ngọt và mềm?', options: ['Chuối', 'Chanh', 'Bưởi', 'Cam xanh'], answer: 'A' },
  { question: 'Trái cây nào có ruột đỏ và nhiều hạt đen?', options: ['Dưa hấu', 'Táo', 'Lê', 'Cam'], answer: 'A' },
  { question: 'Trái cây nào có thể sấy khô để ăn?', options: ['Nho', 'Táo', 'Chuối', 'Tất cả các đáp án trên'], answer: 'D' },
  { question: 'Trái cây nào có thể làm kem trái cây?', options: ['Xoài', 'Dâu', 'Chuối', 'Tất cả các đáp án trên'], answer: 'D' },
  { question: 'Trái cây nào có nhiều chất xơ?', options: ['Táo', 'Chuối', 'Lê', 'Tất cả các đáp án trên'], answer: 'D' },
  { question: 'Trái cây nào thường có vị rất chua?', options: ['Chanh', 'Chuối', 'Táo', 'Xoài chín'], answer: 'A' },
  { question: 'Trái cây nào thường mọc thành chùm trên cây?', options: ['Nho', 'Chuối', 'Táo', 'Lê'], answer: 'A' },
  { question: 'Trái cây nào có vỏ xanh và ruột hồng?', options: ['Ổi hồng', 'Chuối', 'Táo', 'Cam'], answer: 'A' },
  { question: 'Trái cây nào thường được ăn tráng miệng?', options: ['Táo', 'Nho', 'Dưa hấu', 'Tất cả các đáp án trên'], answer: 'D' },
  { question: 'Trái cây nào thường được làm sinh tố ở Việt Nam?', options: ['Xoài', 'Bơ', 'Dâu', 'Tất cả các đáp án trên'], answer: 'D' },
  { question: 'Trái cây nào có vỏ cứng và ruột mềm ngọt?', options: ['Măng cụt', 'Chuối', 'Táo', 'Lê'], answer: 'A' },
  { question: 'Trái cây nào giàu vitamin và tốt cho sức khỏe?', options: ['Trái cây tươi', 'Kẹo', 'Bánh', 'Nước ngọt'], answer: 'A' },

  { question: 'Tên khoa học của táo là gì?', options: ['Malus domestica', 'Mangifera indica', 'Citrus sinensis', 'Vitis vinifera'], answer: 'A' },
  { question: 'Mangifera indica là tên khoa học của trái cây nào?', options: ['Chuối', 'Xoài', 'Cam', 'Lê'], answer: 'B' },
  { question: 'Tên khoa học của chuối là gì?', options: ['Musa spp.', 'Durio zibethinus', 'Psidium guajava', 'Punica granatum'], answer: 'A' },
  { question: 'Citrus sinensis là tên khoa học của trái nào?', options: ['Chanh', 'Cam', 'Bưởi', 'Dứa'], answer: 'B' },
  { question: 'Tên khoa học của nho là gì?', options: ['Vitis vinifera', 'Malus domestica', 'Mangifera indica', 'Citrullus lanatus'], answer: 'A' },
  { question: 'Fragaria × ananassa là tên khoa học của trái nào?', options: ['Cherry', 'Dâu tây', 'Nho', 'Táo'], answer: 'B' },
  { question: 'Tên khoa học của dứa là gì?', options: ['Ananas comosus', 'Musa spp.', 'Psidium guajava', 'Persea americana'], answer: 'A' },
  { question: 'Citrullus lanatus là tên khoa học của trái nào?', options: ['Dưa hấu', 'Cam', 'Chuối', 'Lê'], answer: 'A' },
  { question: 'Tên khoa học của sầu riêng là gì?', options: ['Durio zibethinus', 'Mangifera indica', 'Punica granatum', 'Psidium guajava'], answer: 'A' },
  { question: 'Psidium guajava là tên khoa học của trái nào?', options: ['Ổi', 'Táo', 'Chuối', 'Cam'], answer: 'A' },
  { question: 'Tên khoa học của măng cụt là gì?', options: ['Garcinia mangostana', 'Mangifera indica', 'Vitis vinifera', 'Musa spp.'], answer: 'A' },
  { question: 'Persea americana là tên khoa học của trái nào?', options: ['Bơ', 'Táo', 'Nho', 'Chuối'], answer: 'A' },
  { question: 'Tên khoa học của lựu là gì?', options: ['Punica granatum', 'Malus domestica', 'Musa spp.', 'Psidium guajava'], answer: 'A' },
  { question: 'Selenicereus undatus là tên khoa học của trái nào?', options: ['Thanh long', 'Xoài', 'Chuối', 'Táo'], answer: 'A' },
  { question: 'Tên khoa học của chôm chôm là gì?', options: ['Nephelium lappaceum', 'Durio zibethinus', 'Mangifera indica', 'Persea americana'], answer: 'A' },
  { question: 'Dimocarpus longan là tên khoa học của trái nào?', options: ['Nhãn', 'Vải', 'Táo', 'Chuối'], answer: 'A' },
  { question: 'Tên khoa học của vải là gì?', options: ['Litchi chinensis', 'Mangifera indica', 'Musa spp.', 'Psidium guajava'], answer: 'A' },
  { question: 'Artocarpus heterophyllus là tên khoa học của trái nào?', options: ['Mít', 'Táo', 'Cam', 'Lê'], answer: 'A' },
  { question: 'Tên khoa học của sapoche (hồng xiêm) là gì?', options: ['Manilkara zapota', 'Malus domestica', 'Citrus sinensis', 'Punica granatum'], answer: 'A' },
  { question: 'Averrhoa carambola là tên khoa học của trái nào?', options: ['Khế', 'Táo', 'Chuối', 'Cam'], answer: 'A' },
  { question: 'Malus domestica là tên khoa học của trái nào?', options: ['Táo', 'Lê', 'Cam', 'Nho'], answer: 'A' },
  { question: 'Vitis vinifera là tên khoa học của trái nào?', options: ['Nho', 'Chuối', 'Táo', 'Dứa'], answer: 'A' },
  { question: 'Mangifera indica thuộc loại trái cây nào?', options: ['Xoài', 'Táo', 'Nho', 'Lê'], answer: 'A' },
  { question: 'Durio zibethinus thuộc loại trái cây nào?', options: ['Sầu riêng', 'Cam', 'Chuối', 'Lê'], answer: 'A' },
  { question: 'Citrus limon là tên khoa học của trái nào?', options: ['Chanh', 'Cam', 'Bưởi', 'Táo'], answer: 'A' },
  { question: 'Citrus maxima là tên khoa học của trái nào?', options: ['Bưởi', 'Cam', 'Táo', 'Chuối'], answer: 'A' },
  { question: 'Pyrus communis là tên khoa học của trái nào?', options: ['Lê', 'Táo', 'Chuối', 'Cam'], answer: 'A' },
  { question: 'Ananas comosus là tên khoa học của trái nào?', options: ['Dứa', 'Táo', 'Lê', 'Nho'], answer: 'A' },
  { question: 'Fragaria × ananassa thuộc loại trái cây nào?', options: ['Dâu tây', 'Cherry', 'Táo', 'Cam'], answer: 'A' },
  { question: 'Psidium guajava thuộc loại trái cây nào?', options: ['Ổi', 'Lê', 'Chuối', 'Táo'], answer: 'A' },
];

window.QUIZ_QUESTIONS = QUIZ_QUESTIONS;
